[package]
name = "shiki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
hsl = "0.1.1"
phf = { version = "0.11.1", features = ["macros"] }
